In [1]:
import pandas as pd
import numpy as np

In [2]:
df=pd.read_csv('customer.csv')

In [3]:
df.head()

age  gender   review education purchased
0   30  Female  Average    School        No
1   68  Female     Poor        UG        No
2   70  Female     Good        PG        No
3   72  Female     Good        PG        No
4   16  Female  Average        UG        No

In [4]:
# ignoring age and gender columns
df=df.iloc[:,2:]

In [27]:
df.sample(5)

review education purchased
41   Good        PG       Yes
25   Good    School        No
6    Good    School        No
28   Poor    School        No
18   Good    School        No

In [6]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test=train_test_split(df.iloc[:,0:2],df.iloc[:,-1],
                                                  test_size=0.2)
                                                 

In [7]:
X_train

review education
32  Average        UG
48     Good        UG
15     Poor        UG
20  Average    School
24  Average        PG
0   Average    School
36     Good        UG
25     Good    School
23     Good    School
46     Poor        PG
6      Good    School
16     Poor        UG
17     Poor        UG
9      Good        UG
14     Poor        PG
12     Poor    School
28     Poor    School
43     Poor        PG
10     Good        UG
13  Average    School
44  Average        UG
41     Good        PG
38     Good    School
26     Poor        PG
49     Good        UG
27     Poor        PG
3      Good        PG
8   Average        UG
33     Good        PG
2      Good        PG
1      Poor        UG
7      Poor    School
4   Average        UG
42     Good        PG
39     Poor        PG
31     Poor    School
30  Average        UG
5   Average    School
19     Poor        PG
22     Poor        PG

In [8]:
from sklearn.preprocessing import OrdinalEncoder

In [9]:
oe=OrdinalEncoder(categories=[['Poor','Average','Good'],['School', 'UG', 'PG']])

In [10]:
oe.fit(X_train)

OrdinalEncoder(categories=[['Poor', 'Average', 'Good'], ['School', 'UG', 'PG']])

In [11]:
X_train=oe.transform(X_train)
X_test=oe.transform(X_test)

In [12]:
X_train

array([[1., 1.],
       [2., 1.],
       [0., 1.],
       [1., 0.],
       [1., 2.],
       [1., 0.],
       [2., 1.],
       [2., 0.],
       [2., 0.],
       [0., 2.],
       [2., 0.],
       [0., 1.],
       [0., 1.],
       [2., 1.],
       [0., 2.],
       [0., 0.],
       [0., 0.],
       [0., 2.],
       [2., 1.],
       [1., 0.],
       [1., 1.],
       [2., 2.],
       [2., 0.],
       [0., 2.],
       [2., 1.],
       [0., 2.],
       [2., 2.],
       [1., 1.],
       [2., 2.],
       [2., 2.],
       [0., 1.],
       [0., 0.],
       [1., 1.],
       [2., 2.],
       [0., 2.],
       [0., 0.],
       [1., 1.],
       [1., 0.],
       [0., 2.],
       [0., 2.]])

In [13]:
oe.categories_

[array(['Poor', 'Average', 'Good'], dtype=object),
 array(['School', 'UG', 'PG'], dtype=object)]

In [20]:
# Output Column--> Label encoding is used
# can not decide order in label encoding
from sklearn.preprocessing import LabelEncoder


In [21]:
le=LabelEncoder()

In [22]:
le.fit(y_train)

LabelEncoder()

In [23]:
le.classes_

array([0, 1])

In [24]:
y_train=le.transform(y_test)
y_test=le.transform(y_test)

In [25]:
y_train

array([1, 1, 1, 0, 0, 1, 1, 0, 1, 0], dtype=int64)